version: '3'

services:
  db:
    image: mysql:8.0.39-debian
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tmansur
      - MYSQL_PASSWORD=Teste@12345
    security_opt:
      - seccomp:unconfined #Desabilita restrições do MySQL (não fazer em produção)
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3